### ISSUE TITLE
Micro ros agent stopped at

### ISSUE THREAD

**Issue by czarekk215** [micro-ROS/zephyr_apps#66]
## Issue template

- Hardware description: Wio LoRa E5 dev board
- Zephyr
- Version or commit hash: Humble

## Steps to reproduce the issue
I reproduce steps like on website https://micro.ros.org/docs/tutorials/core/first_application_rtos/zephyr/
I tried pin_pong app and int32_publisher but I used `serial` config
But to run it on my board I added my board name in CMakeList.txt and also changed in microro_tranpsort.h  fd:
```
    // Set the UART used for communication. e.g. {.fd = 0} leads to UART_0 being used.
    static zephyr_transport_params_t default_params = {.fd = 0};
```
to `.fd=1`.
I flash the board by st-link, but for connection I use UART-USB concerter
```
ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_c68cb4bd91ecec11be34ac0ead51a8b2-if00-port0
```

#### Actual behavior
```
[1612884194.563610] info     | TermiosAgentLinux.cpp | init                     | running...             | fd: 3
[1612884194.563954] info     | Root.cpp           | set_verbose_level        | logger setup           | verbose_level: 6
```
#### Expected bahviour
I want to have a new publisher `ping` in ros2 topics, but for now i only have 2 default. This is what I expect:
```
user@user:~$ ros2 topic echo /microROS/ping
stamp:
  sec: 20
  nanosec: 867000000
frame_id: '1344887256_1085377743'
---
stamp:
  sec: 25
  nanosec: 942000000
frame_id: '730417256_1085377743'
---
```
#### Additional information
Is there anything to add or what should I change?
I think the problem is in connection between board and my pc, I work on ubnutu 22.04.3, but I don't know why it's starts to running because if there wasn't connection it would show `waiting for connection`
